import React, { useState, useEffect } from 'react';
import { useNavigate, Link } from 'react-router-dom';
import { supabase } from '../lib/supabase';
import { StateCoverage } from '../components/ds/StateCoverage';
import DashboardShell from '../components/DashboardShell';
import './dashboard.css';

const API_BASE = import.meta.env.VITE_API_URL || 'https://uvicorn-appmain-production-79c6.up.railway.app';

export default function Dashboard() {
  const navigate = useNavigate();
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  const fetchData = async () => {
    setLoading(true);
    setError(null);
    try {
      const { data: { session } } = await supabase.auth.getSession();
      if (!session) {
        navigate('/login');
        return;
      }
      
      const res = await fetch(`${API_BASE}/api/reader/summary`, {
        headers: { 'Authorization': `Bearer ${session.access_token}` }
      });
      
      if (!res.ok) {
        throw new Error('Failed to fetch reader summary');
      }
      
      const json = await res.json();
      setData(json);
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchData();
  }, [navigate]);

  const composeLede = (data) => {
    if (!data) return '';
    if (!data.consent_granted) {
      return "Opt in to tracking to see your reading patterns.";
    }
    const total = data.counters.stories_opened;
    if (total === 0) {
      return "You haven't opened any stories yet.";
    }
    const dist = data.tier_distribution;
    let maxCount = 0;
    let maxTier = 'mainstream';
    if (dist.govt > maxCount) { maxCount = dist.govt; maxTier = 'government-aligned'; }
    if (dist.mainstream > maxCount) { maxCount = dist.mainstream; maxTier = 'mainstream'; }
    if (dist.watchdog > maxCount) { maxCount = dist.watchdog; maxTier = 'watchdog'; }
    
    return `You have opened ${total} stories this week and read <em>mostly ${maxTier}</em> coverage.`;
  };

  const formatDate = (isoString) => {
    const d = new Date(isoString);
    if ((new Date() - d) < 24*60*60*1000) {
      return 'Today';
    }
    return `${d.getDate()} ${d.toLocaleString('default', { month: 'short' })}`;
  };
  
  const handleToggleConsent = async () => {
    if (!data) return;
    try {
      const { data: { session } } = await supabase.auth.getSession();
      await fetch(`${API_BASE}/api/reader/consent`, {
        method: 'POST',
        headers: { 
          'Authorization': `Bearer ${session.access_token}`,
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({ granted: !data.consent_granted })
      });
      fetchData();
    } catch (e) {
      console.error("Failed to toggle consent", e);
    }
  };

  const handleDeleteCounts = async () => {
    if (!window.confirm("Delete your reading counts? This will also turn off tracking.")) return;
    try {
      const { data: { session } } = await supabase.auth.getSession();
      await fetch(`${API_BASE}/api/reader/counts`, {
        method: 'DELETE',
        headers: { 'Authorization': `Bearer ${session.access_token}` }
      });
      fetchData();
    } catch (e) {
      console.error("Failed to delete counts", e);
    }
  };

  return (
    <DashboardShell>
      <div className="dk">
        <div className="main">
          <p className="dateline">Your reading · last 30 days</p>
          
          <StateCoverage loading={loading} error={error} onRetry={fetchData} isEmpty={false}>
            {data && (
              <>
                <p className="lede" dangerouslySetInnerHTML={{ __html: composeLede(data) }}></p>
                <div className="byline">
                  Overview generated by your Coverage Diet. 
                  <span className="ctl" onClick={handleToggleConsent}>{data.consent_granted ? 'Turn tracking off' : 'Turn tracking on'}</span>
                </div>

                {data.consent_granted ? (
                  <>
                    <div className="figs">
                      <div className="fig">
                        <div className="l">Total reads</div>
                        <div className="v">{data.counters.stories_opened}</div>
                        <div className="s">Stories opened</div>
                      </div>
                      <div className="fig">
                        <div className="l">Broadly covered</div>
                        <div className="v">{data.counters.broadly_covered}</div>
                        <div className="s">All tiers reported</div>
                      </div>
                      <div className="fig">
                        <div className="l">Gaps exposure</div>
                        <div className="v gap">{data.counters.one_tier_only}</div>
                        <div className="s">One tier only</div>
                      </div>
                      <div className="fig">
                        <div className="l">Following</div>
                        <div className="v">{data.counters.following}</div>
                        <div className="s">Topics and people</div>
                      </div>
                    </div>

                    <div className="ds">
                      <div className="ds-h">
                        <span className="t">Stories only one tier carried this month</span>
                        <div className="ln"></div>
                        <span className="lk">See all →</span>
                      </div>
                      
                      {(() => {
                        const computedAt = data.public_one_tier_computed_at ? new Date(data.public_one_tier_computed_at) : null;
                        const isStale = computedAt ? (new Date() - computedAt) > (2 * 60 * 60 * 1000) : true;
                        
                        if (isStale) {
                          return <p className="t-muted" style={{ fontSize: '13px', padding: 'var(--s3) 0' }}>The public feed is being refreshed. Check back shortly.</p>;
                        }
                        
                        if (!data.public_one_tier_stories || data.public_one_tier_stories.length === 0) {
                          return <p className="t-muted" style={{ fontSize: '13px', padding: 'var(--s3) 0' }}>No stories available.</p>;
                        }
                        
                        return data.public_one_tier_stories.map(s => (
                          <div className="it" key={s.cluster_id}>
                            <span className="mk mk-dk">One tier</span>
                            <div className="bd">
                              <div className="tt">{s.headline}</div>
                              <div className="mt">{s.evidence || 'Concentrated coverage'}</div>
                            </div>
                            <span className="ag">Live</span>
                          </div>
                        ));
                      })()}
                    </div>
                  </>
                ) : (
                  <div style={{ padding: 'var(--s6) var(--s5)', border: '1px solid var(--border)', borderRadius: '3px', marginTop: 'var(--s5)' }}>
                    <h3 style={{ fontSize: '18px', fontWeight: 600, margin: '0 0 var(--s2)', color: 'var(--ink)' }}>Tracking is off</h3>
                    <p style={{ fontSize: '13px', color: 'var(--t-muted)', margin: '0 0 var(--s4)', lineHeight: 1.6, maxWidth: '60ch' }}>
                      We respect your privacy. TraceNews does not track your reading habits unless you explicitly opt in. Enable tracking to see your coverage diet and exposure to coverage gaps.
                    </p>
                    <button onClick={handleToggleConsent} style={{ background: 'var(--t-primary)', color: 'var(--on-accent)', border: 'none', padding: '8px 16px', borderRadius: '3px', fontWeight: 600, fontSize: '13px', cursor: 'pointer' }}>
                      Enable tracking
                    </button>
                  </div>
                )}
              </>
            )}
          </StateCoverage>
        </div>
        
        <aside className="stand">
          <p className="st-h">Your alerts</p>
          <StateCoverage loading={loading} error={error} isEmpty={data && data.alerts.length === 0} emptyMessage="No recent alerts.">
            {data && data.alerts.length > 0 && data.alerts.map((al, i) => (
              <div className="al" key={i}><b>{al.topic}</b> — {al.message}<span className="ts">{al.time}</span></div>
            ))}
          </StateCoverage>

          <p className="st-h" style={{ marginTop: 'var(--s6)' }}>You follow</p>
          <StateCoverage loading={loading} error={error} isEmpty={data && data.counters.following === 0} emptyMessage="You're not following anything yet">
            {/* Real list is not returned yet, backend just returns a number for follow_count in Phase 2 */}
            {data && data.counters.following > 0 && (
              <div className="fol">
                <span className="n">No items available.</span>
              </div>
            )}
          </StateCoverage>

          <div className="privacy">
            <div className="h">Your data</div>
            <p className="b">Three numbers, nothing more. We never build a list of the stories you opened.</p>
            <span className="a" onClick={handleDeleteCounts} style={{ display: 'flex', gap: '8px' }}>
              <span>Export</span> · 
              <span style={{ textDecoration: 'underline' }}>Delete</span> · 
              <span onClick={handleToggleConsent} style={{ textDecoration: 'underline' }}>{data?.consent_granted ? 'Turn off →' : 'Turn on →'}</span>
            </span>
          </div>
        </aside>
      </div>
    </DashboardShell>
  );
}
