import React, { useState, useEffect } from 'react';
import { useNavigate, Link } from 'react-router-dom';
import { supabase } from '../lib/supabase';
import { StateCoverage } from '../components/ds/StateCoverage';
import './desk.css';

const API_BASE = import.meta.env.VITE_API_URL || 'https://uvicorn-appmain-production-79c6.up.railway.app';

export default function AdminOverview() {
  const navigate = useNavigate();
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  const fetchData = async () => {
    setLoading(true);
    setError(null);
    try {
      const { data: { session } } = await supabase.auth.getSession();
      if (!session) {
        navigate('/login');
        return;
      }
      
      const res = await fetch(`${API_BASE}/api/admin/overview`, {
        headers: { 'Authorization': `Bearer ${session.access_token}` }
      });
      
      if (!res.ok) {
        throw new Error('Failed to fetch admin overview');
      }
      
      const json = await res.json();
      setData(json);
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchData();
  }, [navigate]);

  const composeLede = (figures) => {
    if (!figures) return '';
    const { corrections, verdicts, ingestion } = figures;
    
    let parts = [];
    if (corrections === 0 && verdicts === 0) {
      parts.push("The desk is clear.");
    } else {
      const corrText = corrections === 1 ? "One correction is open" : `${corrections} corrections are open`;
      const verdText = verdicts === 1 ? "one live verdict" : `${verdicts} live verdicts`;
      
      if (corrections > 0 && verdicts > 0) {
        parts.push(`${corrText} and there are <em>${verdText}</em>.`);
      } else if (corrections > 0) {
        parts.push(`${corrText}.`);
      } else {
        parts.push(`There are <em>${verdText}</em>.`);
      }
    }
    
    if (ingestion === "healthy") {
      parts.push("The ingestion wire is healthy.");
    } else {
      parts.push("The ingestion wire status is unknown.");
    }
    
    return parts.join(' ');
  };

  const formatDate = (isoString) => {
    const d = new Date(isoString);
    return `${d.getDate()} ${d.toLocaleString('default', { month: 'short' })} · ${d.getHours().toString().padStart(2, '0')}:${d.getMinutes().toString().padStart(2, '0')}`;
  };

  return (
    <>
      <div className="desk-col">
        <p className="dateline">TraceNews Desk · {new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })}</p>
        
        <StateCoverage loading={loading} error={error} onRetry={fetchData} isEmpty={false}>
          {data && (
            <>
              <p className="lede" dangerouslySetInnerHTML={{ __html: composeLede(data.figures) }}></p>
              <div className="byline">Overview generated by live system state</div>

              <div className="figs">
                <div className="fig">
                  <div className="l">Corrections</div>
                  <div className={`v ${data.figures.corrections > 0 ? 'att' : ''}`}>{data.figures.corrections}</div>
                  <div className="s">Awaiting action</div>
                </div>
                <div className="fig">
                  <div className="l">Verdicts</div>
                  <div className={`v ${data.figures.verdicts > 0 ? 'att' : ''}`}>{data.figures.verdicts}</div>
                  <div className="s">Active non-clear</div>
                </div>
                <div className="fig">
                  <div className="l">Politicians</div>
                  <div className="v">{data.figures.politicians_held}</div>
                  <div className="s">Held for review</div>
                </div>
                <div className="fig">
                  <div className="l">Ingestion</div>
                  <div className="v sm" style={{ color: data.figures.ingestion === 'healthy' ? 'var(--v-clear)' : 'var(--t-muted)' }}>{data.figures.ingestion}</div>
                  <div className="s">Wire status</div>
                </div>
              </div>

              <div className="ds">
                <div className="ds-h">
                  <span className="t">Awaiting Action</span>
                  <div className="ln"></div>
                  <Link to="/admin/corrections" className="lk">View queue</Link>
                </div>
                {data.sections.awaiting_action.length === 0 ? (
                  <p className="t-muted" style={{ fontSize: '13px', padding: 'var(--s3) 0' }}>No open corrections.</p>
                ) : (
                  data.sections.awaiting_action.map(req => (
                    <div className="it" key={req.id}>
                      <span className="mk mk-new">New</span>
                      <div className="bd">
                        <div className="tt">{req.subject_id || 'Unknown source'}</div>
                        <div className="mt">{req.category}</div>
                      </div>
                      <div className="ag">{formatDate(req.created_at)}</div>
                    </div>
                  ))
                )}
              </div>

              <div className="ds">
                <div className="ds-h">
                  <span className="t">Live Verdicts</span>
                  <div className="ln"></div>
                  <Link to="/admin/monitoring-spirit" className="lk">Monitoring Spirit</Link>
                </div>
                {data.sections.live_verdicts.length === 0 ? (
                  <p className="t-muted" style={{ fontSize: '13px', padding: 'var(--s3) 0' }}>No active verdicts.</p>
                ) : (
                  data.sections.live_verdicts.map(v => (
                    <div className="it" key={v.cluster_id}>
                      <span className="mk mk-dk">{v.verdict.toUpperCase()}</span>
                      <div className="bd">
                        <div className="tt">{v.headline}</div>
                        <div className="mt">{v.evidence || 'Concentrated coverage'}</div>
                      </div>
                    </div>
                  ))
                )}
              </div>
            </>
          )}
        </StateCoverage>
      </div>
      
      <aside className="stand">
        <p className="st-h">The Wire</p>
        <StateCoverage loading={loading} error={error} isEmpty={data && data.standing.wire.length === 0} emptyMessage="No wire events.">
          {data && data.standing.wire.length > 0 && (
            <div className="wire">
              {data.standing.wire.map((event, i) => (
                <div key={i}>
                  <span className="t">{formatDate(event.created_at).split('·')[1].trim()}</span> <span className="o">{event.outlet_slug || 'system'}</span> <span className="live">{event.status || 'OK'}</span>
                </div>
              ))}
            </div>
          )}
        </StateCoverage>

        <p className="st-h">Platform</p>
        <StateCoverage loading={loading} error={error} isEmpty={data && Object.keys(data.standing.platform).length === 0} emptyMessage="No platform status available">
          {data && Object.keys(data.standing.platform).length > 0 && (
            <>
              {Object.entries(data.standing.platform).map(([key, value]) => (
                <div className="hb" key={key}>
                  <span style={{ textTransform: 'capitalize' }}>{key.replace('_', ' ')}</span>
                  <span className={`v ${value === 'in sync' || value === 'live' || value === 'stable' || value === 'OK' ? 'ok' : 'warn'}`}>{value}</span>
                </div>
              ))}
            </>
          )}
        </StateCoverage>

        <p className="st-h" style={{ marginTop: 'var(--s6)' }}>Ledger</p>
        <StateCoverage loading={loading} error={error} isEmpty={data && data.standing.ledger.length === 0} emptyMessage="No recent ledger entries.">
          {data && data.standing.ledger.length > 0 && data.standing.ledger.map(entry => (
            <div className="led" key={entry.id}>
              <b>{entry.actor}</b> {entry.action} <b>{entry.subject_name || entry.target_table}</b> — <q>{entry.reason_text}</q>
              <span className="ts">{formatDate(entry.created_at)}</span>
            </div>
          ))}
        </StateCoverage>
      </aside>
    </>
  );
}
